services:
  - type: web
    name: container-validator
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: FLASK_ENV
        value: production
    plan: free
    autoDeploy: true
